Update [Linux Image] Starter Veracode Pipeline

diff --git a/Azure/[Linux Image] Starter Veracode Pipeline b/Azure/[Linux Image] Starter Veracode Pipeline
--- a/Azure/[Linux Image] Starter Veracode Pipeline
+++ b/Azure/[Linux Image] Starter Veracode Pipeline
@@ -1,4 +1,5 @@
 ### NOTE: THIS IS THE MOST *BASIC* VERACODE PIPELINE WITH ALL SCANS FOR DEMO PURPOSES. MUCH MORE CUSTOMISATION IS AVAILABLE! ASK YOUR CSM/CSE or SEE DOCS.VERACODE.COM ###
+# THIS PIPELINE MAKES EXTENSIVE USE OF CONTINUEONERROR:TRUE - THIS IS FOR DEMONSTRATION PURPOSES ONLY. YOU MAY WANT TO FAIL A JOB BASED ON SOME SCAN TYPES #
 
 trigger:
 - none
@@ -25,6 +26,22 @@ jobs:
       testResultsFiles: '**/surefire-reports/TEST-*.xml'
       goals: 'package'
 
+### VERACODE AGENT-BASED SCA ###
+# Generate API token via web UI. Configure using https://docs.veracode.com/r/Setting_Up_Agent_Based_Scans #
+# Set SRCCLR_API_TOKEN as secret variable #
+# Requires SCA product subscription. Scans repo directly, not build artifact. #
+
+- job: AgentbasedSCA
+  steps:
+  - task: CmdLine@2
+    displayName: Conduct Scan
+    env:
+      SRCCLR_API_TOKEN: $(SRCCLR_API_TOKEN)
+    inputs:
+      script: |
+        curl -sSL https://download.sourceclear.com/ci.sh | bash -s - scan --update-advisor --allow-dirty
+    continueOnError: true
+
 ### VERACODE PIPELINE SCAN SAST ###
 # Set API ID & Key as secret variables. Configure further using https://docs.veracode.com/r/r_pipeline_scan_commands #
 # Requires SAST product subscription #
@@ -48,22 +65,6 @@ jobs:
       targetPath: '$(System.DefaultWorkingDirectory)/results.json'
       artifact: 'Pipeline Scan JSON results'
       publishLocation: 'pipeline'
-
-### VERACODE AGENT-BASED SCA ###
-# Generate API token via web UI. Configure using https://docs.veracode.com/r/Setting_Up_Agent_Based_Scans #
-# Set SRCCLR_API_TOKEN as secret variable #
-# Requires SCA product subscription. Scans repo directly, not build artifact. #
-
-- job: AgentbasedSCA
-  steps:
-  - task: CmdLine@2
-    displayName: Conduct Scan
-    env:
-      SRCCLR_API_TOKEN: $(SRCCLR_API_TOKEN)
-    inputs:
-      script: |
-        curl -sSL https://download.sourceclear.com/ci.sh | bash -s - scan --update-advisor --allow-dirty
-    continueOnError: true
 
 ### VERACODE UPLOAD AND SCAN SAST, SCA (TARGETING POLICY OR SANDBOX) ###
 # Install from Azure marketplace, create service connection, configure using https://docs.veracode.com/r/t_install_azure_devops_extension #
@@ -107,3 +108,62 @@ jobs:
       iterationPath: '$(system.teamProject)'
       overwriteIterationPath: true
       flawImportLimit: '1000'
+
+### VERACODE CONTAINER SECURITY IAC, SCA, SBOM ###
+# Requires Container Security Subscription #
+
+- job: ContainerSecurityIaC
+  dependsOn: UploadandScanSASTSCA
+  steps:
+  - task: Bash@3
+    displayName: Conduct Scan
+    inputs:
+      targetType: inline
+      script: |
+        pwd
+        export VERACODE_API_KEY_ID=$(VERACODE_API_ID)
+        export VERACODE_API_KEY_SECRET=$(VERACODE_API_KEY)
+        curl -fsS https://tools.veracode.com/veracode-cli/install | sh
+        ./veracode scan --source $(System.DefaultWorkingDirectory) --type directory --format table --output ./containerresults.txt
+        ./veracode scan --source $(System.DefaultWorkingDirectory) --type directory --format json --output ./containerresults.json
+        ./veracode scan --source $(System.DefaultWorkingDirectory) --type directory --format json --output ./SBOM.json
+        cat ./containerresults.txt
+        echo Generated table, JSON and SBOM artifacts
+    continueOnError: true
+
+  - task: PublishPipelineArtifact@1
+    displayName: Store results as table artifact
+    inputs:
+      targetPath: '$(System.DefaultWorkingDirectory)/containerresults.txt'
+      artifact: 'Container Security .txt results'
+      publishLocation: 'pipeline'
+
+  - task: PublishPipelineArtifact@1
+    displayName: Store results as JSON artifact
+    inputs:
+      targetPath: '$(System.DefaultWorkingDirectory)/containerresults.json'
+      artifact: 'Container Security .json results'
+      publishLocation: 'pipeline'
+
+  - task: PublishPipelineArtifact@1
+    displayName: Store results as SBOM artifact
+    inputs:
+      targetPath: '$(System.DefaultWorkingDirectory)/SBOM.json'
+      artifact: 'Container Security SBOM results'
+      publishLocation: 'pipeline'
+
+  - task: Bash@3
+    displayName: Check Container Policy pass/fail
+    inputs:
+      targetType: 'inline'
+      script: |
+        PASS=$(cat $(System.DefaultWorkingDirectory)/containerresults.json | jq -r '."policy-passed"' )
+        #PASS='passed'
+        echo "Passed policy: $PASS"
+        if [ $PASS == 'false' ]
+        then
+          exit 1
+        else
+          exit 0
+        fi
+    continueOnError: true
